[profile.default]
build_info = true
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config